stages:
  - build
  - report

py38:
  image: python:3.8
  stage: build
  variables:
    TOX_PIP_VERSION: '20.2.4'
  before_script:
    - pip install tox tox-pip-version
  script:
    - tox -e py38-lilac,py38-maple,flake8
  artifacts:
    paths:
      - .coverage*
    expire_in: 5 minutes

coverage:
  image: python:3
  stage: report
  script:
    - pip install coverage
    - python -m coverage combine
    - python -m coverage html
    - python -m coverage report
  coverage: '/TOTAL.*\s+(\d+\.\d+%)$/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week
